---
title: "FSE Dashboard"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: columns
    vertical_layout: fill
    includes:
      in_header: google-analytics.html
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(fse)
  library(flexdashboard)
  library(dplyr)
  library(leaflet)
  library(sf)
  library(viridisLite)
})
```





# FBOs for sale

```{r fbosale-data-test, eval=FALSE}
fbos <- data.frame(
  lon=c(50, -50) , 
  lat=c(-50, 50),
  label = letters[1:2],
  stringsAsFactors = FALSE
)
```

```{r fbosale-data-fetch, eval=!file.exists("fbos.rds")}
fse::fse_fbo_for_sale() %>%
  saveRDS(file="fbos.rds")
```

```{r fbosale-data-load}
readRDS("fbos.rds") %>%
  left_join(icao_data, by=c("Icao"="icao")) %>%
  as_tibble() %>%
  mutate(
    popup = paste(
      Icao, 
      Airport, 
      paste0("Lots: ", Lots), 
      paste0("Gates: ", Gates), 
      paste0("Price: ", format(SellPrice, scientific = FALSE)),
      sep = "<br/>"
    )
  ) -> fbos
```


```{r fbosale-map}
fbos %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(
    lng = ~lon, 
    lat = ~lat, 
    popup = ~popup
  )
```




















# All-In Q400 (table)

```{r allin-q400-fetch, eval=!file.exists("allin-q400.rds")}
fse_aircraft_by_makemodel("Bombardier Dash-8 Q400") %>%
  filter(Location != "In Flight") -> q400
Sys.sleep(1.2)
fse_icao_jobs_from(unique(q400$Location)) %>%
  inner_join(q400, by=c("AircraftId"="SerialNumber")) %>%
  saveRDS("allin-q400.rds")
```

```{r allin-q400-load}
readRDS("allin-q400.rds") %>%
  mutate(
    Pay,
    From = FromIcao, 
    To = ToIcao, 
    What = paste(Amount, Commodity),
    Distance = round(purrr::map2_dbl(From, To, ~icao_distance(c(.x, .y)))),
    `vdol / Distance`  = round(Pay / Distance, 1),
    Expires
  ) -> q400
```

```{r allin-q400-table}
q400 %>%
  select(
    Pay,
    From, 
    To, 
    What,
    Distance,
    `vdol / Distance`,
    Expires
  ) %>%
  arrange(desc(`vdol / Distance`)) %>%
  DT::datatable(escape = FALSE, options = list(paging=FALSE))
```

# All-In Q400 (map)

```{r allin-q400-map}
q400 %>%
  left_join(
    icao_data %>%
      select(
        FromIcao = icao,
        from_lon = lon,
        from_lat = lat
      ),
    by = "FromIcao"
  ) %>%
  left_join(
    icao_data %>%
      select(
        ToIcao = icao,
        to_lon = lon,
        to_lat = lat
      ),
    by = "ToIcao"
  ) %>%
  mutate(
    label = paste(
      paste0(FromIcao, "-", ToIcao),
      paste0("v$", Pay),
      paste0(Distance, " nm"),
      sep = "<br/>"
    )
  ) -> z

z %>%
  with(
    geosphere::gcIntermediate(
      cbind(from_lon, from_lat), cbind(to_lon, to_lat),
      n = 5,
      addStartEnd = TRUE,
      sp = FALSE
    )
  ) -> paths


s <- st_sf(
  data.frame(
    pay = z$Pay, 
    label = z$label
  ), 
  geometry = st_sfc(lapply(paths, st_linestring), crs=4326)
)


pal <- colorBin(
  "inferno", 
  domain = s$pay
  # bins = bins
)

s %>%
  leaflet() %>%
  addTiles() %>%
  addPolylines(
    color = ~ pal(pay),
    popup = ~label
  ) %>%
  addLegend(
    pal = pal,
    values = ~pay
  )
```










# About

FSE data is fetched roughly once every 24 hours. Last fetch on **`r format(fetched_at <- Sys.time(), tz='UTC')`** UTC.

The dashboard is implemented using R and [`fse`](https://github.com/rfse/fse) package.

I am `skybike`. Find me on FSE Discord server.
