name: Make


on:
  push:
    branches: [master]
  schedule: 
    - cron '30 22 * * *' 


jobs:
  render: 
    name: Render dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rmarkdown"))
          remotes::install_deps(dependencies = NA)
        shell: Rscript {0}
      - name: Render dashboard
        run: make 
        env:
          FSE_SERVICE_KEY: ${{ secrets.FSE_SERVICE_KEY }}
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --functions=functions --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
