name: Make


on:
  push:
    branches: [master]


jobs:
  render: 
    name: Render dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Render dashboard
        run: make 
      - name: Publish to Netlify now
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SIDE_ID }}
          NETLIFY_DIR: public
